INSERT INTO regions (id, parent_id, name, created_at, updated_at) VALUES
  ('US', NULL, 'United States', NOW(), NOW()),
  ('US-AL', 'US', 'Alabama', NOW(), NOW()),
  ('US-AZ', 'US', 'Arizona', NOW(), NOW()),
  ('US-AR', 'US', 'Arkansas', NOW(), NOW()),
  ('US-CA', 'US', 'California', NOW(), NOW()),
  ('US-CO', 'US', 'Colorado', NOW(), NOW()),
  ('US-CT', 'US', 'Connecticut', NOW(), NOW()),
  ('US-DE', 'US', 'Delaware', NOW(), NOW()),
  ('US-FL', 'US', 'Florida', NOW(), NOW()),
  ('US-GA', 'US', 'Georgia', NOW(), NOW()),
  ('US-ID', 'US', 'Idaho', NOW(), NOW()),
  ('US-IL', 'US', 'Illinois', NOW(), NOW()),
  ('US-IN', 'US', 'Indiana', NOW(), NOW()),
  ('US-IA', 'US', 'Iowa', NOW(), NOW()),
  ('US-KS', 'US', 'Kansas', NOW(), NOW()),
  ('US-KY', 'US', 'Kentucky', NOW(), NOW()),
  ('US-LA', 'US', 'Louisiana', NOW(), NOW()),
  ('US-ME', 'US', 'Maine', NOW(), NOW()),
  ('US-MD', 'US', 'Maryland', NOW(), NOW()),
  ('US-MA', 'US', 'Massachusetts', NOW(), NOW()),
  ('US-MI', 'US', 'Michigan', NOW(), NOW()),
  ('US-MN', 'US', 'Minnesota', NOW(), NOW()),
  ('US-MS', 'US', 'Mississippi', NOW(), NOW()),
  ('US-MO', 'US', 'Missouri', NOW(), NOW()),
  ('US-MT', 'US', 'Montana', NOW(), NOW()),
  ('US-NE', 'US', 'Nebraska', NOW(), NOW()),
  ('US-NV', 'US', 'Nevada', NOW(), NOW()),
  ('US-NH', 'US', 'New Hampshire', NOW(), NOW()),
  ('US-NJ', 'US', 'New Jersey', NOW(), NOW()),
  ('US-NM', 'US', 'New Mexico', NOW(), NOW()),
  ('US-NY', 'US', 'New York', NOW(), NOW()),
  ('US-NC', 'US', 'North Carolina', NOW(), NOW()),
  ('US-ND', 'US', 'North Dakota', NOW(), NOW()),
  ('US-OH', 'US', 'Ohio', NOW(), NOW()),
  ('US-OK', 'US', 'Oklahoma', NOW(), NOW()),
  ('US-OR', 'US', 'Oregon', NOW(), NOW()),
  ('US-PA', 'US', 'Pennsylvania', NOW(), NOW()),
  ('US-RI', 'US', 'Rhode Island', NOW(), NOW()),
  ('US-SC', 'US', 'South Carolina', NOW(), NOW()),
  ('US-SD', 'US', 'South Dakota', NOW(), NOW()),
  ('US-TN', 'US', 'Tennessee', NOW(), NOW()),
  ('US-TX', 'US', 'Texas', NOW(), NOW()),
  ('US-UT', 'US', 'Utah', NOW(), NOW()),
  ('US-VT', 'US', 'Vermont', NOW(), NOW()),
  ('US-VA', 'US', 'Virginia', NOW(), NOW()),
  ('US-WA', 'US', 'Washington', NOW(), NOW()),
  ('US-WV', 'US', 'West Virginia', NOW(), NOW()),
  ('US-WI', 'US', 'Wisconsin', NOW(), NOW()),
  ('US-WY', 'US', 'Wyoming', NOW(), NOW()),
  ('US-DC', 'US', 'District of Columbia', NOW(), NOW());
