INSERT INTO regions (id, parent_id, name, created_at, updated_at) VALUES
  ('AT', NULL, 'Austria', NOW(), NOW()),
  ('AL', NULL, 'Albania', NOW(), NOW()),
  ('BY', NULL, 'Belarus', NOW(), NOW()),
  ('BE', NULL, 'Belgium', NOW(), NOW()),
  ('BA', NULL, 'Bosnia and Herzegovina', NOW(), NOW()),
  ('BG', NULL, 'Bulgaria', NOW(), NOW()),
  ('CA', NULL, 'Canada', NOW(), NOW()),
  ('HR', NULL, 'Croatia', NOW(), NOW()),
  ('CR', NULL, 'Czechia', NOW(), NOW()),
  ('DK', NULL, 'Denmark', NOW(), NOW()),
  ('EE', NULL, 'Estonia', NOW(), NOW()),
  ('FI', NULL, 'Finland', NOW(), NOW()),
  ('FR', NULL, 'France', NOW(), NOW()),
  ('DE', NULL, 'Germany', NOW(), NOW()),
  ('GI', NULL, 'Gibraltar', NOW(), NOW()),
  ('GR', NULL, 'Greece', NOW(), NOW()),
  ('HU', NULL, 'Hungary', NOW(), NOW()),
  ('IS', NULL, 'Iceland', NOW(), NOW()),
  ('IR', NULL, 'Ireland', NOW(), NOW()),
  ('IT', NULL, 'Italy', NOW(), NOW()),
  ('LV', NULL, 'Latvia', NOW(), NOW()),
  ('LT', NULL, 'Lithuania', NOW(), NOW()),
  ('LU', NULL, 'Luxembourg', NOW(), NOW()),
  ('MK', NULL, 'Republic of North Macedonia', NOW(), NOW()),
  ('MT', NULL, 'Malta', NOW(), NOW()),
  ('MD', NULL, 'Moldova', NOW(), NOW()),
  ('ME', NULL, 'Montenegro', NOW(), NOW()),
  ('NL', NULL, 'Netherlands', NOW(), NOW()),
  ('NO', NULL, 'Norway', NOW(), NOW()),
  ('PT', NULL, 'Portugal', NOW(), NOW()),
  ('PL', NULL, 'Poland', NOW(), NOW()),
  ('RO', NULL, 'Romania', NOW(), NOW()),
  ('RU', NULL, 'Russian Federation', NOW(), NOW()),
  ('RS', NULL, 'Serbia', NOW(), NOW()),
  ('SK', NULL, 'Slovakia', NOW(), NOW()),
  ('SI', NULL, 'Slovenia', NOW(), NOW()),
  ('ES', NULL, 'Spain', NOW(), NOW()),
  ('SE', NULL, 'Sweden', NOW(), NOW()),
  ('CH', NULL, 'Switzerland', NOW(), NOW()),
  ('UA', NULL, 'Ukraine', NOW(), NOW());
