CREATE TABLE authorized_users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  github_user_login VARCHAR(40) UNIQUE NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
